<?xml version="1.0" encoding="utf-8"?><Database Name="goodworld" Class="DataClasses_GoodWorldDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LOCKTHBNK-DUSIP\SQLEXPRESS2016;Initial Catalog=goodworld;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PortalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblBillingDetails" Member="tblBillingDetails">
    <Type Name="tblBillingDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BillingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblXtraReports" Member="tblXtraReports">
    <Type Name="tblXtraReport">
      <Column Name="ReportID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LayoutData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GUID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblBillingPayment" Member="tblBillingPayments">
    <Type Name="tblBillingPayment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PolicyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblBillingRegister" Member="tblBillingRegisters">
    <Type Name="tblBillingRegister">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BillingNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BillingName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BillingType" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TaxID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaxP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DiscountP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblBrokerage" Member="tblBrokerages">
    <Type Name="tblBrokerage">
      <Column Name="BRID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InsurerCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PolicyType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRCommP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PRCommP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblBrokeragePaymentRegister" Member="tblBrokeragePaymentRegisters">
    <Type Name="tblBrokeragePaymentRegister">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Branchid" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Accountcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AgentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AGENT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MainClass" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubClass" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Dftxno" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="InsureName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ApproveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReceivePremium" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BrokerCommAmt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="WageCommAmt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="WageOVAmt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AgentCommAmt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NetPayment" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RVDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BrokerSurveyAmt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BB" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblCarBrandModel" Member="tblCarBrandModels">
    <Type Name="tblCarBrandModel">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CarBrand" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CarModel" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblCarType" Member="tblCarTypes">
    <Type Name="tblCarType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InsureType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblClaimRegister" Member="tblClaimRegisters">
    <Type Name="tblClaimRegister">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PolicyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CarLicensePlate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GrossPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ClaimNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccidentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AccisentPlace" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AccidentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsRight" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ClaimAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblInsurer" Member="tblInsurers">
    <Type Name="tblInsurer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InsurerCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InsurerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BranchCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CertificateNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblInsureType" Member="tblInsureTypes">
    <Type Name="tblInsureType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Commission" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblLogin_Log" Member="tblLogin_Logs">
    <Type Name="tblLogin_Log">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPolicyRegister" Member="tblPolicyRegisters">
    <Type Name="tblPolicyRegister">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InsurerCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IdentityNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TelNo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="InsureType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PolicyType" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Suminsured" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Premium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Vat" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Stamp" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GrossPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="BRCommP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="BRCommAmt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PRCommP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PRCommAmt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SubCommP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SubCommAmt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SubCommID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SentPolicyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GetPolicyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SubGetPolicyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CarLicensePlate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CarRegYear" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SocialMediaNo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="BenefitName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NewRenew" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="RenewPolicyYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CarType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CarBrandModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Engine" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Chassis" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CarSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChassisType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CarUse" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="DriverName1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DriverDOB1" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DriverName2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DriverDOB2" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SendPolicy2CustomerDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CustomerGetPolicyDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPolicyType" Member="tblPolicyTypes">
    <Type Name="tblPolicyType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InsureType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblReceiptDetails" Member="tblReceiptDetails">
    <Type Name="tblReceiptDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceiptDetails" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblReceiptPremium" Member="tblReceiptPremiums">
    <Type Name="tblReceiptPremium">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceiptTitle" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ReceiptPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblReceiptRegister" Member="tblReceiptRegisters">
    <Type Name="tblReceiptRegister">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptNo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaxNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsurerCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ChequeNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChequeBranch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Brach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubAgent" Member="tblSubAgents">
    <Type Name="tblSubAgent">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubAgentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubAgentName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CertificateNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubAgentComm" Member="tblSubAgentComms">
    <Type Name="tblSubAgentComm">
      <Column Name="SubAgentCommID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubAgentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsureType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubAgentCommP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubBillingPayment" Member="tblSubBillingPayments">
    <Type Name="tblSubBillingPayment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PolicyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubBillingPolicy" Member="tblSubBillingPolicies">
    <Type Name="tblSubBillingPolicy">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubBillingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Commission" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Premium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CommissionAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="BillingAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubBillingPremium" Member="tblSubBillingPremiums">
    <Type Name="tblSubBillingPremium">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubBillingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubBillingTitle" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubBillingPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubBillingRegister" Member="tblSubBillingRegisters">
    <Type Name="tblSubBillingRegister">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BillingDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubBroker" Member="tblSubBrokers">
    <Type Name="tblSubBroker">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AgentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CertificateNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubComm" Member="tblSubComms">
    <Type Name="tblSubComm">
      <Column Name="SubCommID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsureType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubCommP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUWBillingPolicy" Member="tblUWBillingPolicies">
    <Type Name="tblUWBillingPolicy">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaymentBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PaymentNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PolicyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UWBillingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRCommP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="BRCommAmt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="VAT7Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TAX3Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ServiceFreeP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ServiceFreeAmt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ServiceFreeVAT7Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ServiceFreeTAX3Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUWBillingPremium" Member="tblUWBillingPremiums">
    <Type Name="tblUWBillingPremium">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UWBillingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UWBillingTitle" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UWBillingPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUWBillingRegister" Member="tblUWBillingRegisters">
    <Type Name="tblUWBillingRegister">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InsurerCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BillingDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_BillingDetails" Member="v_BillingDetails">
    <Type Name="v_BillingDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BillingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BillingNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BillingName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BillingType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaxP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DiscountP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="InsurerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InsureType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CarLicensePlate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chassis" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Suminsured" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Premium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Vat" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Stamp" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GrossPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NewRenew" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AgentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Brokerage" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="BrokerageAmt" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Monthly" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CertificateNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_UWBillingRegister" Member="v_UWBillingRegisters">
    <Type Name="v_UWBillingRegister">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsurerCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InsurerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BillingDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BRCommAmt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="VAT7Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TAX3Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ServiceFreeAmt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ServiceFreeVAT7Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ServiceFreeTAX3Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_BillingPayment" Member="v_BillingPayments">
    <Type Name="v_BillingPayment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PolicyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InsurerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InsureType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CarLicensePlate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chassis" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Suminsured" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Premium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Vat" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Stamp" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GrossPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NewRenew" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AgentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Brokerage" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="BrokerageAmt" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Monthly" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CertificateNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_BillingRegister" Member="v_BillingRegisters">
    <Type Name="v_BillingRegister">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BillingNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BillingName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BillingType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaxID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaxP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DiscountP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_BrokeragePayment" Member="v_BrokeragePayments">
    <Type Name="v_BrokeragePayment">
      <Column Name="AGENT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Branchid" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Account" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceivePremium" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="WageOVAmt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BrokerSurveyAmt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NetPayment" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BB" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_ReceiptRegister" Member="v_ReceiptRegisters">
    <Type Name="v_ReceiptRegister">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TaxNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsurerCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsurerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ReceiveCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ChequeNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChequeBranch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BrachCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BrachName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_Report" Member="v_Reports">
    <Type Name="v_Report">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsurerCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsurerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InsureType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="InsureTypeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CarLicensePlate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chassis" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Suminsured" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Premium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Vat" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Stamp" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GrossPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NewRenew" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AgentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Brokerage" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="BrokerageAmt" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Monthly" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CustomerType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CertificateNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_Report1" Member="v_Report1s">
    <Type Name="v_Report1">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsurerCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsurerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InsureType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="InsureTypeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CarLicensePlate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chassis" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Suminsured" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Premium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Vat" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Stamp" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GrossPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NewRenew" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AgentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Brokerage" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="BrokerageAmt" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Monthly" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CustomerType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CertificateNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_SubBillingDetails" Member="v_SubBillingDetails">
    <Type Name="v_SubBillingDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubBillingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Commission" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CommissionAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="BillingAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="InsurerCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsurerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InsureType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="InsureTypeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CarLicensePlate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chassis" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Suminsured" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Premium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Vat" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Stamp" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GrossPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NewRenew" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AgentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Brokerage" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="BrokerageAmt" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Monthly" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CustomerType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CertificateNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_SubBillingPayment" Member="v_SubBillingPayments">
    <Type Name="v_SubBillingPayment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PolicyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Commission" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CommissionAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="BillingAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="InsurerCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsurerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InsureType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="InsureTypeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CarLicensePlate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chassis" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Suminsured" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Premium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Vat" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Stamp" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GrossPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NewRenew" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AgentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Brokerage" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="BrokerageAmt" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Monthly" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CustomerType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CertificateNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_SubBillingRegister" Member="v_SubBillingRegisters">
    <Type Name="v_SubBillingRegister">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AgentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BillingDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CommissionAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_UserTabs" Member="v_UserTabs">
    <Type Name="v_UserTab">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TabId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TabName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TabOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Permission" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PortalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PortalCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PortalName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Sortpath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IconID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PageId" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_UWBillingPolicy" Member="v_UWBillingPolicies">
    <Type Name="v_UWBillingPolicy">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PaymentNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PolicyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BRCommP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="BRCommAmt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="VAT7Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TAX3Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ServiceFreeP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ServiceFreeAmt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ServiceFreeVAT7Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ServiceFreeTAX3Amt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TotalPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="InsurerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InsureType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CarLicensePlate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chassis" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Suminsured" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Premium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Vat" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Stamp" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GrossPremium" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NewRenew" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AgentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Brokerage" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="BrokerageAmt" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Monthly" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CertificateNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>